Unnamed: 0,rectype,issueid,project_owner,project_name,actor,time,text,action,title
4,issue_comment,390,pycqa,astroid,coveralls,2017-01-26 06:45:30,"
[![Coverage Status](https://coveralls.io/builds/9850372/badge)](https://coveralls.io/builds/9850372)

Coverage decreased (-2.2%) to 87.126% when pulling **abf03d062a53208d662a973c34cd395907c1987d on euresti:brain_typing_namedtuple** into **a9430c92981124e1868c525a29f053f0d7661e4b on PyCQA:master**.
",nan,nan
9,pull_request_commit_comment,390,pycqa,astroid,PCManticore,2017-02-09 09:00:07,This can raise ``InferenceError``. We need to catch it and raise ``UseInferenceDefault`` instead.,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
10,pull_request_commit_comment,390,pycqa,astroid,PCManticore,2017-02-13 22:20:58,Why would this block raise AttributeError?,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
11,pull_request_commit_comment,390,pycqa,astroid,euresti,2017-02-17 14:50:18,"Well I'm not checking whether `node.args[1]` actually has an `elts` Or whether that elt has more elts in `elt.elts[0]`
  ",cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
12,pull_request_commit_comment,390,pycqa,astroid,euresti,2017-02-17 14:50:57,I'll fix this.,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
13,pull_request_commit_comment,390,pycqa,astroid,rogalski,2017-02-19 20:06:22,Decorate it with `@test_utils.require_version('3.6')`,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/tests/unittest_brain.py')"
14,pull_request_commit_comment,390,pycqa,astroid,rogalski,2017-02-19 20:09:10,Maybe moving it just above actual usage is a good idea?,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
15,pull_request_commit_comment,390,pycqa,astroid,rogalski,2017-02-19 20:11:11,"I'd limit catching AttributeErrpr just to `node.args[1].elts`.

Can you clarify second statement in comment above?",cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
5,issue_comment,390,pycqa,astroid,rogalski,2017-02-28 19:35:09,@euresti are you willing to make tests all tests pass and finish up this change? It would be nice to have it before releasing Pylint 1.7.0 (first release wih Python 3.6 support).,nan,nan
6,issue_comment,390,pycqa,astroid,euresti,2017-03-01 00:38:25,Sorry for the delay I'll work on this today or tomorrow.,nan,nan
16,pull_request_commit_comment,390,pycqa,astroid,euresti,2017-03-01 00:47:39,"`node.args[1].elts` can raise an AttributeError if node.args[1] is not a Tuple.
`elt.elts` can also raise an AttributeError if node.args[1] is a Tuple but doesn't have a Tuple inside it.

I can add a bunch of isinstance checks if you like.
",cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
17,pull_request_commit_comment,390,pycqa,astroid,euresti,2017-03-01 00:48:08,Technically typing is available in python2 also but in pypi.  Though for tests maybe I should limit it to 3.6,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/tests/unittest_brain.py')"
18,pull_request_commit_comment,390,pycqa,astroid,euresti,2017-03-01 00:48:28,Will do,cfe156629037195eeb43181efa5bdd09eb15c1c0,"(None, '', u'astroid/brain/brain_typing.py')"
7,issue_comment,390,pycqa,astroid,euresti,2017-03-01 06:51:16,Ok hope that's good enough.  ,nan,nan
8,issue_comment,390,pycqa,astroid,PCManticore,2017-03-01 09:17:04,Thanks so much @euresti for this! Thank you @rogalski for helping with the review.,nan,nan
 , , , , , , , , , 
 , , , , , , , , , 
2,issue_comment,395,pycqa,astroid,degustaf,2017-01-30 15:41:33,"@sscherfke I can see from your traceback that you are using Python3.6, which isn't officially supported yet.  Do you get the same error with other versions of Python?",nan,nan
3,issue_comment,395,pycqa,astroid,sscherfke,2017-01-30 19:01:45,Haven’t tried yet – will do it tomorrow. But since Py36 support is on your roadmap anyways. ;-),nan,nan
4,issue_comment,395,pycqa,astroid,degustaf,2017-01-30 19:45:57,@sscherfke Not trying to suggest it won't get done.  Just trying to better understand the issue :),nan,nan
5,issue_comment,395,pycqa,astroid,ceridwen,2017-01-30 20:22:20,What version of pandas is this with?  I can't replicate this error on Python 2.7 or 3.5 with pandas 0.19.2. For now I'm tagging this issue with 3.6.,nan,nan
6,issue_comment,395,pycqa,astroid,sscherfke,2017-01-31 07:39:34,"Hm. I can reproduce this with the system's Python 2.7 and 3.5 as well:
```console
$ mktmpenv --python=/usr/bin/python3
$ pip install pandas
Successfully installed numpy-1.12.0 pandas-0.19.2 python-dateutil-2.6.0 pytz-2016.10
$ pip install git+https://github.com/PyCQA/astroid@d0b5acdfebcdda5c949584c32a8cbc0f31d5cf25
Successfully installed astroid-1.5.0 lazy-object-proxy-1.2.2 wrapt-1.10.8
$ pip install git+https://github.com/PyCQA/pylint@7daed7b8982480c868b0f642a5251f00ffb253c6
Successfully installed editdistance-0.3.1 isort-4.2.5 mccabe-0.6.1 pylint-2.0.0
$ cat /tmp/pylinttest.py
import pandas
pandas.read_sql('spam', engine=None)['key'].value
$ pylint --version
pylint 2.0.0,
astroid 1.5.0
Python 3.5.2 (default, Oct 14 2016, 12:54:53)
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)]
$ pylint /tmp/pylinttest.py
************* Module pylinttest
W:  2, 0: Expression ""pandas.read_sql('spam', engine=None)['key'].value"" is assigned to nothing (expression-not-assigned)
Traceback (most recent call last):
  File ""/.virtualenvs/tmp-b168b6a226f0cec/bin/pylint"", line 11, in <module>
    load_entry_point('pylint==2.0.0', 'console_scripts', 'pylint')()
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/__init__.py"", line 13, in run_pylint
    Run(sys.argv[1:])
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/lint.py"", line 1300, in __init__
    linter.check(args)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/lint.py"", line 726, in check
    self._do_check(files_or_modules)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/lint.py"", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/lint.py"", line 934, in check_astroid_module
    walker.walk(ast_node)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/utils.py"", line 973, in walk
    self.walk(child)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/utils.py"", line 973, in walk
    self.walk(child)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/utils.py"", line 970, in walk
    cb(astroid)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/pylint/checkers/typecheck.py"", line 612, in visit_attribute
    infered = list(node.expr.infer())
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/astroid/decorators.py"", line 85, in wrapped
    res = next(generator)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/astroid/decorators.py"", line 138, in raise_if_nothing_inferred
    yield next(generator)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/astroid/inference.py"", line 260, in infer_subscript
    assigned = value.getitem(index_value, context)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/astroid/scoped_nodes.py"", line 1523, in getitem
    methods = dunder_lookup.lookup(self, '__getitem__')
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/astroid/interpreter/dunder_lookup.py"", line 54, in lookup
    return _class_lookup(node, name)
  File ""/.virtualenvs/tmp-b168b6a226f0cec/lib/python3.5/site-packages/astroid/interpreter/dunder_lookup.py"", line 67, in _class_lookup
    target=node
astroid.exceptions.AttributeInferenceError: '__getitem__' not found on <ClassDef.generator l.0 at 0x7fe311ffdbe0>.
```",nan,nan
7,issue_comment,395,pycqa,astroid,rr-,2017-02-05 14:01:39,"Minimal example

```python
from typing import Dict

def test(params: Dict[str, str]):
    pass
```
",nan,nan
 , , , , , , , , , 
 , , , , , , , , , 
4,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 21:54:01,"
[![Coverage Status](https://coveralls.io/builds/10042723/badge)](https://coveralls.io/builds/10042723)

Coverage decreased (-2.03%) to 87.275% when pulling **edee41c6ffbc7fddbfada91b7d0b069a46b6d648 on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
5,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 21:57:34,"
[![Coverage Status](https://coveralls.io/builds/10042781/badge)](https://coveralls.io/builds/10042781)

Coverage decreased (-2.03%) to 87.275% when pulling **df99e25f292aa987f6c533f461666095781e6eed on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
6,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 22:01:48,"
[![Coverage Status](https://coveralls.io/builds/10042803/badge)](https://coveralls.io/builds/10042803)

Coverage increased (+0.008%) to 89.311% when pulling **df99e25f292aa987f6c533f461666095781e6eed on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
7,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 22:09:01,"
[![Coverage Status](https://coveralls.io/builds/10042923/badge)](https://coveralls.io/builds/10042923)

Coverage increased (+0.008%) to 89.311% when pulling **30dad28076353d8890b6542e60117d6205fc97ba on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
8,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 22:09:01,"
[![Coverage Status](https://coveralls.io/builds/10042923/badge)](https://coveralls.io/builds/10042923)

Coverage increased (+0.008%) to 89.311% when pulling **30dad28076353d8890b6542e60117d6205fc97ba on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
9,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 22:09:01,"
[![Coverage Status](https://coveralls.io/builds/10042923/badge)](https://coveralls.io/builds/10042923)

Coverage increased (+0.008%) to 89.311% when pulling **30dad28076353d8890b6542e60117d6205fc97ba on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
10,issue_comment,400,pycqa,astroid,coveralls,2017-02-07 22:09:01,"
[![Coverage Status](https://coveralls.io/builds/10042923/badge)](https://coveralls.io/builds/10042923)

Coverage increased (+0.008%) to 89.311% when pulling **30dad28076353d8890b6542e60117d6205fc97ba on rogalski:async_comprehensions** into **9ee1f58ba91a52148829a781f3bfcff6f659139e on PyCQA:master**.
",nan,nan
15,pull_request_commit_comment,400,pycqa,astroid,PCManticore,2017-02-09 08:18:36,Let's put ``is_async`` in ``_other_fields``. ``_astroid_fields`` is only for objects which are AST objects.,714abcc4758ff2120a0824533a2d075a8a57da69,"(None, '', u'astroid/node_classes.py')"
16,pull_request_commit_comment,400,pycqa,astroid,PCManticore,2017-02-09 08:19:58,``' '.join('if %s' % n.accept(self) for i in ...)`` feels more natural to me.,714abcc4758ff2120a0824533a2d075a8a57da69,"(None, '', u'astroid/as_string.py')"
17,pull_request_commit_comment,400,pycqa,astroid,PCManticore,2017-02-09 08:20:42,"Check my previous comment regarding ``is_async``. Sorry, I think I misled you in a different PR, with a similar use case.",714abcc4758ff2120a0824533a2d075a8a57da69,"(None, '', u'astroid/rebuilder.py')"
18,pull_request_commit_comment,400,pycqa,astroid,PCManticore,2017-02-09 08:23:48,"You can use ``@`` to extract a particular node, instead of doing it manually, such as in this example:

```
f = extract_node('''
async def f():
   return [i async for i in...] #@
''')
# now f is the Return
```
Or you can use ``__()`` for a fine grained approach, as in:

```
f = extract_node('''
async def f():
   return __([i async for i in...])
''')
# now f is the comprehension
```",714abcc4758ff2120a0824533a2d075a8a57da69,"(None, '', u'astroid/tests/unittest_python3.py')"
19,pull_request_commit_comment,400,pycqa,astroid,PCManticore,2017-02-09 08:24:25,"A comment should be enough here. If I remember correctly, docstrings have special meaning in unittests.",714abcc4758ff2120a0824533a2d075a8a57da69,"(None, '', u'astroid/tests/unittest_python3.py')"
11,issue_comment,400,pycqa,astroid,rogalski,2017-02-09 18:44:30,"@PCManticore thanks for the review, see new commits for fixes",nan,nan
12,issue_comment,400,pycqa,astroid,rogalski,2017-02-14 20:38:25,"@PCManticore since dunder for async iterables is `__aiter__` and not `__iter__`, I'd expect that by default some stuff will fail. I'll try to come up with a test case, but I haven't used asyncio at all, so it may take a while.",nan,nan
13,issue_comment,400,pycqa,astroid,PCManticore,2017-03-01 09:26:59,"@rogalski I think we can merge this as is, and create a new issue for adding support for ``__aiter__`` and async comprehension's ``assigned_stmts``. ",nan,nan
14,issue_comment,400,pycqa,astroid,rogalski,2017-03-01 11:43:46,"@PCManticore agreed. I'll do a merge commit, just so all tests can complete successfully and _squash and merge_ it afterwards.",nan,nan
 , , , , , , , , , 
 , , , , , , , , , 
4,issue_comment,408,pycqa,astroid,PCManticore,2017-03-01 09:23:36,"I don't think that this is the root cause of that bug. In the reproducing example provided there, the package had a ``__init__.py`` file. We should check where astroid is raising the ImportError in the first place, in order to know what triggers the bug.",nan,nan
5,issue_comment,408,pycqa,astroid,rogalski,2017-03-05 09:20:08,"@PCManticore Well, all I know is that it fixes reported issue. I'm just no sure where is a place for an automated test.",nan,nan
 , , , , , , , , , 
 , , , , , , , , , 
4,issue_comment,409,pycqa,astroid,asottile,2017-02-28 21:38:45,Seems to be left over from this commit: https://github.com/PyCQA/astroid/commit/8ed837d828692db5b95b3e906bebeacbc68c256f,nan,nan
5,issue_comment,409,pycqa,astroid,PCManticore,2017-03-01 09:18:50,Thank you!,nan,nan
 , , , , , , , , , 
 , , , , , , , , , 
