rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,1505,nilearn,nilearn,mohitsharma916,2017-09-03 18:42:42,"I was trying to visualize the MRI images from MICCAI 2012 Grand Challenge on Multi-Atlas Labeling.
This is what I was trying to do:

`from nilearn.plotting import plot_anat`
`plot_anat(filename)`

This is the error I am getting.

> File ""<stdin>"", line 1, in <module>
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/plotting/img_plotting.py"", line 482, in plot_anat
>     dim=dim, black_bg=black_bg)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/plotting/img_plotting.py"", line 368, in _load_anat
>     anat_img = _utils.check_niimg_3d(anat_img)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/_utils/niimg_conversions.py"", line 322, in check_niimg_3d
>     return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/_utils/niimg_conversions.py"", line 271, in check_niimg
>     niimg = load_niimg(niimg, dtype=dtype)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nilearn/_utils/niimg.py"", line 110, in load_niimg
>     niimg = nibabel.load(niimg)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/loadsave.py"", line 45, in load
>     return image_klass.from_filename(filename, **kwargs)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/keywordonly.py"", line 17, in wrapper
>     return func(*args, **kwargs)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/analyze.py"", line 1001, in from_filename
>     return klass.from_file_map(file_map, mmap=mmap)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/keywordonly.py"", line 17, in wrapper
>     return func(*args, **kwargs)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/analyze.py"", line 971, in from_file_map
>     img._affine = header.get_best_affine()
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/nifti1.py"", line 731, in get_best_affine
>     return self.get_qform()
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/nifti1.py"", line 915, in get_qform
>     quat = self.get_qform_quaternion()
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/nifti1.py"", line 890, in get_qform_quaternion
>     return fillpositive(bcd, self.quaternion_threshold)
>   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nibabel/quaternions.py"", line 99, in fillpositive
>     raise ValueError('w2 should be positive, but is %e' % w2)
> ValueError: w2 should be positive, but is -6.401211e-07

When I open the same file using MIPAV, I have no issues.

Does this look like a bug in nilearn or am I missing something.

I have attached the file I was using.
[1000_3.nii.gz](https://github.com/nilearn/nilearn/files/1273129/1000_3.nii.gz)


",start issue,Error in loading nifti image,I tri visual mri imag miccai 2012 grand challeng multiatla label thi I tri thi error I get when I open file use mipav I issu doe look like bug nilearn I miss someth I attach file I use 10003niigz
issue_closed,1505,nilearn,nilearn,KamalakerDadi,2017-09-06 11:36:27,,closed issue,Error in loading nifti image,
issue_comment,1505,nilearn,nilearn,agramfort,2017-09-03 18:50:24,"you should report this issue to nibabel : https://github.com/nipy/nibabel

check first that you have the latest version of nibabel.
",,,report issu nibabel check first latest version nibabel
issue_comment,1505,nilearn,nilearn,KamalakerDadi,2017-09-03 18:53:23,"We use nibabel support to load Nifti images before plotting. So, I feel the same. This issue should be reported/asked in nibabel tracking issues.",,,We use nibabel support load nifti imag plot So I feel thi issu reportedask nibabel track issu
issue_comment,1505,nilearn,nilearn,KamalakerDadi,2017-09-03 19:06:20,"Try like this before plotting. It worked for me.
```python
import numpy as np
import nibabel as nib
nib.Nifti1Header.quaternion_threshold = -np.finfo(np.float32).eps * 10  # notice new minus sign

from nilearn import plotting
plotting.plot_anat('1000_3.nii.gz')
```
I had a look at this [thread](https://mail.python.org/pipermail/neuroimaging/2016-January/000731.html)",,,tri like plot It work I look thread
issue_comment,1505,nilearn,nilearn,mohitsharma916,2017-09-03 19:48:24,"@KamalakerDadi That actually worked for me. 

This way this doesn't look like a bug. Because people at Nibabel are already aware of this case, I don't think reporting it again would be helpful.

Anyway, thanks for the help.",,,kamalakerdadi that actual work thi way doesnt look like bug becaus peopl nibabel alreadi awar case I dont think report would help anyway thank help
