rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,294,pycqa,astroid,ceridwen,2015-12-12 17:31:32,"While I was debugging the merge of modular-locals into 2.0, there was a call to nodes.const_factory in const_infer_binary_op, which didn't exist any more.  I'm not sure where, but there was an except: clause catching the AttributeError inappropriately at some point during the inference, which made it very hard to debug.
",start issue,Narrow exception handling for AttributeErrors in the inference to avoid concealing bugs,while I debug merg modularloc 20 call nodesconstfactori constinferbinaryop didnt exist Im sure except claus catch attributeerror inappropri point infer made hard debug
issue_closed,294,pycqa,astroid,PCManticore,2016-01-03 08:44:16,,closed issue,Narrow exception handling for AttributeErrors in the inference to avoid concealing bugs,
