rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,139,pycqa,astroid,pylint-bot,2015-06-30 00:48:18,"Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

---

```
#!python

# The tuple is iterable, it should work
lines = []
lines += (1, 2, 3) 
```

Of course, the lack of understanding flow controls leads to spurious false positives for this situation as well.

---
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/139
",start issue,False positives for unsupported-binary-operation,origin report claudiu popa bitbucket pcmanticor github pcmanticor Of cours lack understand flow control lead spuriou fals posit situat well bitbucket
issue_comment,139,pycqa,astroid,pylint-bot,2015-07-03 13:17:20,"_Original comment by_ **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**:

---

As an example of an error caused by the lack of understanding flow control:

```
#!python

 if isinstance(default, tuple):
       return default + (n, )
   else:
       return default + [n] # thinks its tuple

```
",,,origin comment claudiu popa bitbucket pcmanticor github pcmanticor As exampl error caus lack understand flow control
