rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,127,pycqa,astroid,pylint-bot,2015-06-20 15:09:20,"Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

---

Currently, doing this will result in `module` having `print_function` as a local:

```
#!python

from __future__ import print_function
```

---
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/127
",start issue,__future__ statements should not be locals of the module,origin report claudiu popa bitbucket pcmanticor github pcmanticor current result local bitbucket
issue_closed,127,pycqa,astroid,pylint-bot,2015-12-09 05:53:51,,closed issue,__future__ statements should not be locals of the module,
issue_comment,127,pycqa,astroid,pylint-bot,2015-07-07 09:00:33,"_Original comment by_ **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**:

---

Actually it's not a problem at all, since print_function will be available as an object in that module.
",,,origin comment claudiu popa bitbucket pcmanticor github pcmanticor actual problem sinc printfunct avail object modul
